---
header:
  -
    name: Dashboard
    url: /
  - 
    name: Results & trends
    url: /results-and-trends
    # dropdown:
    #   -
    #     name: Example 1
    #     url: /example-1
    #   -
    #     name: Example 2
    #     url: /example-2
    #   -
    #     name: Example 3
    #     url: /example-3
  -
    name: My account
    url: /account
  -
    name: Log out
    url: /account
footer:
  -
    name: Home
    url: /
  -
    name: About
    url: /about